# -*- coding: utf-8 -*-
"""Training.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_TG0gyrtBrmRnmJRg5xr0ubXIGOZw2vL

**Train the Model**
"""

from joblib.numpy_pickle import dump
import os
import logging
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv
from joblib import dump

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

def trained_model():
  try:

    # load the content from .env file to env variables
    load_dotenv(dotenv_path='/content/sample_data/env/.env')

    project_root_env = os.getenv("PROJECT_ROOT")
    if project_root_env is None:
        raise ValueError("PROJECT_ROOT environment variable not set. Please ensure it's defined in your .env file.")
    PROJECT_ROOT = Path(project_root_env)

    DATASET_PATH = PROJECT_ROOT /os.getenv("DATASET_NAME")
    MODEL_PATH = PROJECT_ROOT /os.getenv("MODEL_DIR") / os.getenv("MODEL_NAME")

    LOG_PATH = PROJECT_ROOT / os.getenv("LOG_DIR") / os.getenv("LOG_NAME")

    print(LOG_PATH)
    print(MODEL_PATH)

    TARGET_COL = os.getenv("TARGET_COL")
    TEST_SIZE = float(os.getenv("TEST_SIZE"))
    RANDOM_STATE = int(os.getenv("RANDOM_STATE"))

    MODEL_PATH.parent.mkdir(parents=True, exist_ok=True);
    LOG_PATH.parent.mkdir(parents=True, exist_ok=True);

    logging.basicConfig(
        level = logging.INFO,
        format = "%(asctime)s - %(levelname)s - %(message)s",
        handlers = [
            logging.FileHandler(LOG_PATH),
            logging.StreamHandler()
        ],
        force=True
    )

    logging.info("Training Script Started.")
    df = pd.read_csv(DATASET_PATH)
    logging.info(f"Dataset loaded with shape {df.shape}")

    X = df.drop(TARGET_COL, axis=1)
    y = df[TARGET_COL]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=TEST_SIZE, random_state=RANDOM_STATE, stratify=y)

    pipeline = Pipeline(steps=[("scaler", StandardScaler()),("classifier", LogisticRegression())])

    pipeline.fit(X_train, y_train)

    logging.info("Model training completed.")

    train_accuracy = accuracy_score(y_train, pipeline.predict(X_train))
    test_accuracy = accuracy_score(y_test, pipeline.predict(X_test))

    logging.info(f"Train Accuracy: {train_accuracy: .3f}")
    logging.info(f"Test Accuracy: {test_accuracy: .3f}")

    train_report = classification_report(y_train, pipeline.predict(X_train))
    test_report = classification_report(y_test, pipeline.predict(X_test))

    logging.info("Train Classification Report:")
    logging.info(train_report)

    logging.info("Test Classification Report:")
    logging.info(test_report)

    dump(pipeline, MODEL_PATH)

    logging.info(f"Model saved successfully to {MODEL_PATH}.")
    logging.info("Training Script finished.")

  except Exception as e:

    print(f"Training failed: {e}")
    logging.exception(f"Training script failed: {e}")
    raise


if __name__ == "__main__":
  trained_model()

"""### Check Log File Content

Let's read the content of the generated `app.log` file to see if the logging was successful.
"""

log_file_path = '/content/sample_data/logs/app.log'

try:
    with open(log_file_path, 'r') as f:
        log_content = f.read()
    if log_content:
        print("Content of app.log:")
        print(log_content)
    else:
        print(f"The log file '{log_file_path}' exists but is empty.")
except FileNotFoundError:
    print(f"The log file '{log_file_path}' was not found.")
except Exception as e:
    print(f"An error occurred while reading the log file: {e}")